name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actionsx/prettier@v3
        name: Run prettier
        with:
          args: --check ui

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --no-config --disable-all --enable gosimple --enable errcheck --enable govet --enable unused --enable goconst --enable godot --timeout 3m

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -mod=vendor -v --race -covermode=atomic -coverprofile cover.out ./...
